'use client'

import { useState } from 'react'
import { ArrowRight, Check, ChevronDown } from 'lucide-react'
import { AuthFrame } from '@/app/auth/auth-shell'

const roles = ['Property Buyer','Investor','Real Estate Developer','Architect','Lawyer','Urban Planner','Other']
export default function ProfileSetupPage() {
  const [name, setName] = useState(''); const [role, setRole] = useState(''); const [city, setCity] = useState(''); const valid = name.trim().length > 1 && role
  return <AuthFrame back="/verify-otp"><div className="mb-9"><div className="mb-8 flex items-center gap-3 font-mono text-[10px] tracking-[.2em] text-white/40"><span className="text-primary">01</span><span className="h-px w-8 bg-primary" /><span>02</span><span className="ml-2">PROFILE</span></div><p className="font-mono text-[10px] tracking-[.28em] text-primary">PERSONALIZE YOUR SIGNAL</p><h2 className="mt-5 text-4xl font-black tracking-[-.06em] sm:text-5xl">Tell us a little about yourself.</h2><p className="mt-4 text-sm leading-6 text-white/50">We&apos;ll tune your UrbanScope view around what matters to you.</p></div><form onSubmit={e => { e.preventDefault(); if (valid) window.location.href = '/explore' }} className="flex flex-col gap-5"><label className="flex flex-col gap-2 text-xs text-white/50">FULL NAME<input required value={name} onChange={e => setName(e.target.value)} placeholder="Your name" className="rounded-xl border border-white/15 bg-white/[.03] px-4 py-4 text-base text-white outline-none transition focus:border-primary focus:shadow-[0_0_25px_rgba(255,106,0,.16)]" /></label><label className="flex flex-col gap-2 text-xs text-white/50">PROFESSION<div className="relative"><select required value={role} onChange={e => setRole(e.target.value)} className="w-full appearance-none rounded-xl border border-white/15 bg-[#111] px-4 py-4 text-base text-white outline-none transition focus:border-primary"><option value="">Select your role</option>{roles.map(x => <option key={x}>{x}</option>)}</select><ChevronDown className="pointer-events-none absolute right-4 top-1/2 size-4 -translate-y-1/2 text-primary" /></div></label><label className="flex flex-col gap-2 text-xs text-white/50">PRIMARY CITY <span className="text-[10px] text-white/25">OPTIONAL</span><input value={city} onChange={e => setCity(e.target.value)} placeholder="e.g. Surat" className="rounded-xl border border-white/15 bg-white/[.03] px-4 py-4 text-base text-white outline-none transition focus:border-primary focus:shadow-[0_0_25px_rgba(255,106,0,.16)]" /></label><button disabled={!valid} className="btn-glow mt-3 flex items-center justify-center gap-2 rounded-xl px-5 py-4 text-sm font-bold text-black disabled:cursor-not-allowed disabled:opacity-35">Enter UrbanScope <ArrowRight className="size-4" /></button></form><div className="mt-8 flex items-center gap-2 text-xs text-white/35"><Check className="size-4 text-primary" /> Your profile stays private and helps personalize insights.</div></AuthFrame>
}
