'use client'

import { useEffect, useRef, useState } from 'react'
import { ArrowRight, RotateCcw } from 'lucide-react'
import { AuthFrame, LocationPulse } from '@/app/auth/auth-shell'

export default function VerifyOtpPage() {
  const [digits, setDigits] = useState(['','','','','','']); const [seconds, setSeconds] = useState(28); const refs = useRef<(HTMLInputElement | null)[]>([])
  useEffect(() => { if (seconds <= 0) return; const id = setInterval(() => setSeconds(s => s - 1), 1000); return () => clearInterval(id) }, [seconds])
  const update = (i: number, value: string) => { const next = value.replace(/\D/g, '').slice(-1); const copy = [...digits]; copy[i] = next; setDigits(copy); if (next && i < 5) refs.current[i + 1]?.focus() }
  const complete = digits.every(Boolean)
  return <AuthFrame><div className="mb-10"><p className="font-mono text-[10px] tracking-[.28em] text-primary">SECURE VERIFICATION</p><h2 className="mt-5 text-4xl font-black tracking-[-.06em] sm:text-5xl">Verify your number</h2><p className="mt-4 text-sm leading-6 text-white/50">We sent a 6-digit code to<br /><span className="text-white/80">+91 {new URLSearchParams(typeof window !== 'undefined' ? window.location.search : '').get('phone') || '98765 43210'}</span></p><a href="/login" className="mt-4 inline-block text-xs text-primary underline underline-offset-4">Change number</a></div><form onSubmit={e => { e.preventDefault(); if (complete) window.location.href = '/profile-setup' }} className="flex flex-col gap-7"><div className="flex justify-between gap-2">{digits.map((digit, i) => <input key={i} ref={el => { refs.current[i] = el }} aria-label={`Digit ${i + 1}`} inputMode="numeric" value={digit} onChange={e => update(i, e.target.value)} onPaste={e => { e.preventDefault(); const pasted = e.clipboardData.getData('text').replace(/\D/g,'').slice(0,6).split(''); setDigits([...pasted, ...Array(6-pasted.length).fill('')]); refs.current[Math.min(pasted.length,5)]?.focus() }} className="size-11 rounded-xl border border-white/15 bg-white/[.03] text-center text-2xl font-bold outline-none transition focus:border-primary focus:shadow-[0_0_25px_rgba(255,106,0,.2)] sm:size-14" />)}</div><div className="flex items-center justify-between text-xs"><span className="text-white/40">{seconds > 0 ? `Resend code in 00:${String(seconds).padStart(2,'0')}` : 'You can request a new code'}</span><button type="button" disabled={seconds > 0} onClick={() => setSeconds(28)} className="flex items-center gap-2 text-primary disabled:opacity-30"><RotateCcw className="size-3" /> Resend OTP</button></div><button disabled={!complete} className="btn-glow flex items-center justify-center gap-2 rounded-xl px-5 py-4 text-sm font-bold text-black disabled:cursor-not-allowed disabled:opacity-35">Verify & Continue <ArrowRight className="size-4" /></button></form><div className="mt-12 flex items-center gap-3 border-t border-white/10 pt-5 text-xs text-white/35"><LocationPulse /> Your number is used only to secure your access.</div></AuthFrame>
}
